### ISSUE TITLE
Configuration Settings for Default Paste Action

### ISSUE THREAD

**Issue by EddieOne** [cleditor/cleditor#28]
When pasting from word or from the web a bunch on unwanted code is inserted. It would be great to have an option to set a default for paste actions, if possible of course. 

I'm not alone here, these people have the same problem, https://groups.google.com/forum/?fromgroups=#!topic/cleditor/lVtpoWOGf2o

**Comment by jzabroski** [comment]
I wonder if someone has developed a general purpose "Word to text" copy-paste utility in JavaScript.  Arguably the best work-around would be to allow someone to upload a word document and do the transformation in the language of your choice.

It looks as though a user on Google Groups contributed the following solution sketch:

```javascript
   $doc.bind("paste", function(e) {
        e.preventDefault();
        
        // Changes the unformatted text replacing new lines with break tags
        var text = e.originalEvent.clipboardData.getData('Text').replace(/\n/g, "<br />");
        if (text !== "") {
            execCommand(editor, 'inserthtml', text, null);
            focus(editor);
        }
    
        return false;
    });
```
