### ISSUE TITLE
IE8: Paste as text submission results in 'unspecified error'

### ISSUE THREAD

**Issue by barneycarroll** [cleditor/cleditor#29]
Line 715, char 7.

This is an old bug:
https://groups.google.com/forum/?fromgroups=#!topic/cleditor/mTLtCq-KEes

…and seems to have been a problem for the other major DHTML editors too:
http://ckeditor.com/forums/CKEditor-3.x/Copy-Paste-error-IE8

**Comment by jzabroski** [comment]
Closing.  IE8 is no longer supported by Microsoft.
