### ISSUE TITLE
Crashing in IE 8

### ISSUE THREAD

**Issue by anandsumeet** [cleditor/cleditor#33]
I am using the latest release v1.4.3
In IE8 it crashes the browser (working fine in IE9 and above), the behavior is erratic. 
- At times it happens if I click outside the editor and then when I click back inside the editor (onfocus)
- sometimes just by fast clicking inside the editor it happens
- sometime while typing text it shows the text inside the editor after a lag and after typing a few lines it crashes the browser

My application is very ajax heavy, using JQ1.7+, JQ-UI 1.10+, twitter bootstrap, JQ fileupload plugin, handlbars.js and flot.js
Total JS size uncompressed  in dom is approx 1 MB

**Comment by jzabroski** [comment]
Closing.  IE8 no longer receives updates from Microsoft, and Microsoft IE (across all versions) has less than 7% of browser share according to Wikipedia. https://www.microsoft.com/en-us/windowsforbusiness/end-of-ie-support
