### ISSUE TITLE
Editor not working if container is initially hidden

### ISSUE THREAD

**Issue by mr-unicoder** [cleditor/cleditor#38]
CLEditor is a great tool but i've faced a very annoying problem that the editor doesn't work if its parent is initially hidden.
To reproduce the issue, Add a [textarea] element inside a [div] element
then set [display] attribute to [none] for the [div]
Try to display the [div] on button click, The editor will not work.
What i'm trying to do is to get the editor initially hidden and get displayed under specific conditions.

**Comment by jzabroski** [comment]
This is not really an issue with cl-editor and more an issue with the fact you are not giving cleditor a layout with which to expand.  Closing.
